### PR TITLE
Bump to node20

### LINKED ISSUE #65: Node 16 deprecation warning
As noted here: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/ actions need to now use Node 20. As of yesterday, using this action causes a deprecation warning. It should be updated to Node 20.

### PR DESCRIPTION
**Pull request by suttonjames**
Closes #65

### CODE REVIEW

**Comment by ggrossetie** [comment]
Thanks!

**Comment by elyobo** [comment]
New release neded @ggrossetie?

**Comment by ggrossetie** [comment]
https://github.com/yuzutech/annotations-action/releases/tag/v0.5.0

**Comment by elyobo** [comment]
Thanks!

**Pull request merged**
